/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "adc.h"
#include "uart.h"

#define VREF        3.3f
#define ADC_RES     4095.0f     // 12-bit ADC resolution

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
    UartInit(9600);
    AdcInit();
    UartPuts("Temperature Sensor (LM35)\r\n");

    while (1) {
        uint16_t adc_val = AdcRead();


        float voltage = (VREF * adc_val) / ADC_RES;


        float temperature = voltage * 100.0f;

        char str[64];
        sprintf(str, "ADC: %u | V: %.2f V | Temp: %.2f °C\r\n", adc_val, voltage, temperature);
        UartPuts(str);

        DelayMs(1000);
    }
}





