/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include "adc.h"
#include "uart.h"

#define VREF        3.3f
#define ADC_RES     4095.0f
#define R_FIXED     10000.0f

#define A 44550.0f   // LDR constant A (adjust after calibration)
#define B 0.676f        // LDR constant B (adjust after calibration)

int main(void) {
    UartInit(9600);
    AdcInit();
    UartPuts("LDR Light Intensity\r\n");

    while (1) {
        uint16_t adc_val = AdcRead();
        float voltage = (VREF * adc_val) / ADC_RES;
        if (voltage == 0) voltage = 0.001f;

        float r_ldr = R_FIXED * (VREF - voltage) / voltage;


        float lux = powf((A / r_ldr), (1.0f / B));

        char str[80];
        sprintf(str, "ADC=%u, V=%.2fV, R_LDR=%.0f Ohm, Lux=%.2f\r\n", adc_val, voltage, r_ldr, lux);
        UartPuts(str);

        DelayMs(1000);
    }
}



